[versions]
compose = "1.8.0-beta01"
androidx-lifecycle = "2.8.0-rc03"
kotlin = "2.1.10"
vlcj = "4.10.1"
app-version = "1.0.9"
room = "2.7.0-alpha13"
room-sqlite-bundled = "2.5.0-alpha13"
ksp = "2.1.10-1.0.29"
jupnp = "3.0.3"
androidx-navigation = "2.7.0-alpha06"
image-loader = '1.10.0'


[libraries]
vlcj = { module = "uk.co.caprica:vlcj", version.ref = "vlcj" }
roomRuntime = { module = "androidx.room:room-runtime", version.ref = "room" }
roomCompiler = { module = "androidx.room:room-compiler", version.ref = "room" }
roomGuava = { module = "androidx.room:room-guava", version.ref = "room" }
roomKtx = { module = "androidx.room:room-ktx", version.ref = "room" }
roomBundled = { module = "androidx.sqlite:sqlite-bundled", version.ref = "room-sqlite-bundled" }
jupnp-bom-compile = { module = "org.jupnp.bom:org.jupnp.bom.compile", version.ref = "jupnp"}
jupnp-osgi = { module = "org.jupnp:org.jupnp.osgi", version.ref = "jupnp" }
jupnp-support = { module = "org.jupnp:org.jupnp.support", version.ref = "jupnp" }
androidx-lifecycle-runtime-compose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel-compose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
androidx-navigation-compose = { module = "org.jetbrains.androidx.navigation:navigation-compose", version.ref = "androidx-navigation" }
image-loader = {module = "io.github.qdsfdhvh:image-loader", version.ref = "image-loader"}


[plugins]
jetbrainsCompose = { id = "org.jetbrains.compose", version.ref = "compose" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
room = { id = "androidx.room", version.ref = "room" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }