[versions]
compose = "1.8.0-beta01"
androidx-lifecycle = "2.8.0-rc03"
junit = "4.13.2"
kotlin = "2.1.10"
vlcj = "4.10.1"
app-version = "1.0.7"
sqldelight = "2.0.2"
conveyor = "2.1"
room = "2.7.0-alpha13"
room-sqlite-bundled = "2.5.0-alpha13"
ksp = "2.1.10-1.0.29"
jupnp = "3.0.3"
androidx-navigation = "2.7.0-alpha06"
jetty = "12.0.16"
image-loader = '1.10.0'


[libraries]
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
vlcj = { module = "uk.co.caprica:vlcj", version.ref = "vlcj" }
roomRuntime = { module = "androidx.room:room-runtime", version.ref = "room" }
roomCompiler = { module = "androidx.room:room-compiler", version.ref = "room" }
roomGuava = { module = "androidx.room:room-guava", version.ref = "room" }
roomKtx = { module = "androidx.room:room-ktx", version.ref = "room" }
roomBundled = { module = "androidx.sqlite:sqlite-bundled", version.ref = "room-sqlite-bundled" }
jupnp-bom-compile = { module = "org.jupnp.bom:org.jupnp.bom.compile", version.ref = "jupnp"}
jupnp-bom = { module = "org.jupnp.bom:org.jupnp.bom", version.ref = "jupnp" }
jupnp-osgi = { module = "org.jupnp:org.jupnp.osgi", version.ref = "jupnp" }
#jupnp-tool = { module = "org.jupnp.pom:tools", version.ref = "jupnp"}
jupnp-bom-runtime = { module = "org.jupnp:org.jupnp.runtime" }
jupnp-bundles = { module = "org.jupnp.pom:bundles", version.ref = "jupnp" }
jupnp = { module = "org.jupnp:jupnp", version.ref = "jupnp" }
jupnp-support = { module = "org.jupnp:org.jupnp.support", version.ref = "jupnp" }
jetty-servlet = { module = "org.eclipse.jetty.ee10:jetty-ee10-servlet", version.ref = "jetty"}
jetty-server = { module = "org.eclipse.jetty.http2:jetty-http2-server", version.ref = "jetty"}
jetty-client = { module = "org.eclipse.jetty:jetty-client", version.ref = "jetty"}
androidx-lifecycle-runtime-compose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel-compose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
androidx-navigation-compose = { module = "org.jetbrains.androidx.navigation:navigation-compose", version.ref = "androidx-navigation" }
image-loader = {module = "io.github.qdsfdhvh:image-loader", version.ref = "image-loader"}


[plugins]
jetbrainsCompose = { id = "org.jetbrains.compose", version.ref = "compose" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
sqldelight = { id = "app.cash.sqldelight", version.ref = "sqldelight" }
conveyor = { id = "dev.hydraulic.conveyor", version.ref = "conveyor" }
room = { id = "androidx.room", version.ref = "room" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
platform = { id = "java-platform"}